name: podcasts
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  eva_icons_flutter: ^3.0.0
  ionicons: ^0.1.2
  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  build_runner: ^2.1.1
  lottie: ^1.2.1
  http: ^0.13.4
  fluttertoast: ^8.0.8
  audio_service: ^0.18.0
  just_audio: ^0.9.13
  intl: ^0.17.0
  hive: ^2.0.4
  hive_generator: ^1.1.1
  path_provider: ^2.0.7
  step_progress_indicator: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Louis
      fonts:
        - asset: assets/fonts/louis.ttf
